version: '3.7'
services:
  app:
    image: hello:latest
    networks:
      - proxy
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.hello_https.rule=Host(`hello.dev.mta4.ru`)"
        - "traefik.http.routers.hello_https.entrypoints=https"
        - "traefik.http.routers.hello_https.tls=true"
        - "traefik.http.routers.hello_https.tls.options=mintls13@file"
        - "traefik.http.routers.hello_https.service=hello"
        - "traefik.http.services.hello.loadbalancer.server.port=8000"
        - "traefik.http.services.hello.loadbalancer.passhostheader=true"
      placement:
        constraints:
          # - node.role == manager
          - node.role == worker
          - node.labels.hello == true
networks:
  proxy:
    external: true
