# Static configuration
# https://docs.traefik.io/reference/static-configuration/file/

global:
  checkNewVersion: false
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true
  maxIdleConnsPerHost: "10"
  forwardingTimeouts:
    dialTimeout: "30s"
    responseHeaderTimeout: "10s"
    idleConnTimeout: "180s"

entryPoints:
  http:
    address: ":80"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: "10s"
        graceTimeOut: "10s"
      respondingTimeouts:
        readTimeout: "10s"
        writeTimeout: "10s"
        idleTimeout: "360s"
  https:
    address: ":443"
      lifeCycle:
        requestAcceptGraceTimeout: "10s"
        graceTimeOut: "10s"
      respondingTimeouts:
        readTimeout: "10s"
        writeTimeout: "10s"
        idleTimeout: "360s"
  traefik:
    address: ":8080"
      lifeCycle:
        requestAcceptGraceTimeout: "10s"
        graceTimeOut: "10s"
      respondingTimeouts:
        readTimeout: "10s"
        writeTimeout: "10s"
        idleTimeout: "360s"

log:
  level: "DEBUG" # DEBUG, INFO, WARN, ERROR, FATAL, PANIC
  filePath: "/logs/traefik/traefik.log"
  format: "common"

accessLog:
  filePath: "/logs/traefik/access.log"
  format: "common"
  bufferingSize: "100"
#   fields:
#     defaultMode: "keep"
#     headers:
#       defaultMode: "keep"
#       names:
#           # User-Agent: redact
#           Authorization: drop
#           # Content-Type: keep

api:
  insecure: false
  dashboard: true
  debug: false

ping:
  entryPoint: "traefik"

providers:
  providersThrottleDuration: "2s"
  file:
    filename: "/etc/traefik/traefik.dynamic.yml"
    watch: true
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    swarmMode: true
    exposedByDefault: false
    # useBindPortIP: false
    network: "proxy"
    swarmModeRefreshSeconds: "15s"
  rest:
    insecure: true

# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: your-email@your-domain.org
#       storage: "/certificates/acme/acme.json"
#       httpChallenge:
#         entryPoint: "http"
